sit:
  1:
    head_p: -0.0
    head_y: 0.0
    l_arm_el_y: -29.98
    l_arm_grip: 59.96
    l_arm_sh_p1: 25.03
    l_arm_sh_p2: 5.0
    l_arm_sh_r: 75.02
    l_arm_wr_p: -0.0
    l_arm_wr_r: -0.0
    l_arm_wr_y: -0.0
    l_leg_an_p: 3.95
    l_leg_an_r: -4.02
    l_leg_hip_p: -79.62
    l_leg_hip_r: -0.07
    l_leg_hip_y: 0.79
    l_leg_kn_p: 83.31
    r_arm_el_y: 30.02
    r_arm_grip: 59.96
    r_arm_sh_p1: -25.0
    r_arm_sh_p2: -5.02
    r_arm_sh_r: -75.01
    r_arm_wr_p: 0.0
    r_arm_wr_r: 0.0
    r_arm_wr_y: -0.0
    r_leg_an_p: -5.8
    r_leg_an_r: -3.16
    r_leg_hip_p: 80.29
    r_leg_hip_r: 3.16
    r_leg_hip_y: 0.03
    r_leg_kn_p: -83.06
    time: 0
    torso_y: 0.0
    velocity: 5
  2:
    head_p: 0.0
    head_y: 0.0
    l_arm_el_y: -37.14
    l_arm_grip: 59.96
    l_arm_sh_p1: -36.01
    l_arm_sh_p2: 2.43
    l_arm_sh_r: 90.26
    l_arm_wr_p: 1.97
    l_arm_wr_r: 1.36
    l_arm_wr_y: 7.89
    l_leg_an_p: -9.49
    l_leg_an_r: -0.91
    l_leg_hip_p: -80.82
    l_leg_hip_r: -1.28
    l_leg_hip_y: -19.32
    l_leg_kn_p: 71.83
    r_arm_el_y: 27.52
    r_arm_grip: 59.96
    r_arm_sh_p1: 33.58
    r_arm_sh_p2: -1.02
    r_arm_sh_r: -87.77
    r_arm_wr_p: 0.0
    r_arm_wr_r: 1.18
    r_arm_wr_y: 15.08
    r_leg_an_p: 9.92
    r_leg_an_r: -3.1
    r_leg_hip_p: 84.88
    r_leg_hip_r: 4.42
    r_leg_hip_y: 16.54
    r_leg_kn_p: -69.15
    time: 0
    torso_y: -0.0
    velocity: 5
standby:
  1:
    head_p: 0.0
    head_y: 0.0
    l_arm_el_y: -30.0
    l_arm_grip: 59.96
    l_arm_sh_p1: 25.0
    l_arm_sh_p2: 5.0
    l_arm_sh_r: 75.01
    l_arm_wr_p: -0.0
    l_arm_wr_r: -0.0
    l_arm_wr_y: 0.0
    l_leg_an_p: 29.07
    l_leg_an_r: -0.01
    l_leg_hip_p: -32.39
    l_leg_hip_r: 0.0
    l_leg_hip_y: -0.0
    l_leg_kn_p: 61.48
    r_arm_el_y: 30.01
    r_arm_grip: 59.96
    r_arm_sh_p1: -24.99
    r_arm_sh_p2: -5.01
    r_arm_sh_r: -75.01
    r_arm_wr_p: 0.0
    r_arm_wr_r: 0.0
    r_arm_wr_y: -0.0
    r_leg_an_p: -29.07
    r_leg_an_r: -0.0
    r_leg_hip_p: 32.41
    r_leg_hip_r: -0.0
    r_leg_hip_y: 0.0
    r_leg_kn_p: -61.48
    time: 0
    torso_y: -0.01
    velocity: 5
test:
  1:
    head_p: 0.0
    head_y: 0.0
    l_arm_el_y: -30.59
    l_arm_grip: 59.96
    l_arm_sh_p1: 19.8
    l_arm_sh_p2: 5.01
    l_arm_sh_r: 81.62
    l_arm_wr_p: 0.0
    l_arm_wr_r: -0.0
    l_arm_wr_y: -2.28
    l_leg_an_p: 29.1
    l_leg_an_r: -0.01
    l_leg_hip_p: -20.06
    l_leg_hip_r: 0.58
    l_leg_hip_y: 0.02
    l_leg_kn_p: 32.3
    r_arm_el_y: 32.92
    r_arm_grip: 59.96
    r_arm_sh_p1: -20.45
    r_arm_sh_p2: -5.02
    r_arm_sh_r: -81.98
    r_arm_wr_p: 0.0
    r_arm_wr_r: 0.0
    r_arm_wr_y: 0.33
    r_leg_an_p: -29.07
    r_leg_an_r: -0.01
    r_leg_hip_p: 19.98
    r_leg_hip_r: 0.0
    r_leg_hip_y: 3.38
    r_leg_kn_p: -29.85
    time: 0
    torso_y: 0.03
    velocity: 5
