hello:
  1:
    head_p: 0.0
    head_y: 0.0
    l_arm_el_y: 30.0
    l_arm_finger45_p: -180.0
    l_arm_index_p: -180.0
    l_arm_middle_p: -180.0
    l_arm_sh_p1: 25.0
    l_arm_sh_p2: 5.0
    l_arm_sh_r: 75.0
    l_arm_thumb_p: -180.0
    l_arm_thumb_y: 0.0
    l_arm_wr_p: 0.0
    l_arm_wr_r: 0.0
    l_arm_wr_y: 0.0
    r_arm_el_y: -30.0
    r_arm_finger45_p: -180.0
    r_arm_index_p: -180.0
    r_arm_middle_p: -180.0
    r_arm_sh_p1: -25.0
    r_arm_sh_p2: -4.99
    r_arm_sh_r: -75.0
    r_arm_thumb_p: -180.0
    r_arm_thumb_y: 0.0
    r_arm_wr_p: 0.0
    r_arm_wr_r: 0.0
    r_arm_wr_y: 0.0
    time: 0
    torso_y: 0.0
    velocity: 5
  2:
    head_p: 0.0
    head_y: 0.0
    l_arm_el_y: 30.0
    l_arm_finger45_p: -180
    l_arm_index_p: -180
    l_arm_middle_p: -180
    l_arm_sh_p1: 0
    l_arm_sh_p2: 5.0
    l_arm_sh_r: 75.0
    l_arm_thumb_p: -180
    l_arm_thumb_y: 0.0
    l_arm_wr_p: 0.0
    l_arm_wr_r: 0.0
    l_arm_wr_y: 0.0
    r_arm_el_y: -30.0
    r_arm_finger45_p: -180
    r_arm_index_p: -180
    r_arm_middle_p: -180
    r_arm_sh_p1: 0
    r_arm_sh_p2: -5.0
    r_arm_sh_r: -75.0
    r_arm_thumb_p: -180
    r_arm_thumb_y: 0.0
    r_arm_wr_p: 0.0
    r_arm_wr_r: 0.0
    r_arm_wr_y: 0.0
    time: 0
    torso_y: 0.0
    velocity: 5
  3:
    head_p: 0.0
    head_y: 0.0
    l_arm_el_y: 60.0
    l_arm_finger45_p: -180
    l_arm_index_p: -180
    l_arm_middle_p: -180
    l_arm_sh_p1: -18
    l_arm_sh_p2: 5.0
    l_arm_sh_r: 75.0
    l_arm_thumb_p: -180
    l_arm_thumb_y: 0.0
    l_arm_wr_p: 0.0
    l_arm_wr_r: 180.0
    l_arm_wr_y: 0.0
    r_arm_el_y: -60
    r_arm_finger45_p: -180
    r_arm_index_p: -180
    r_arm_middle_p: -180
    r_arm_sh_p1: 18
    r_arm_sh_p2: -5.0
    r_arm_sh_r: -75.0
    r_arm_thumb_p: -180
    r_arm_thumb_y: 0.0
    r_arm_wr_p: 0.0
    r_arm_wr_r: -180.0
    r_arm_wr_y: 0.0
    time: 0
    torso_y: 0.0
    velocity: 5
  4:
    head_p: 0.0
    head_y: 0.0
    l_arm_el_y: 60.0
    l_arm_finger45_p: -180
    l_arm_index_p: -180
    l_arm_middle_p: -180
    l_arm_sh_p1: -18.01
    l_arm_sh_p2: 5.0
    l_arm_sh_r: 74.99
    l_arm_thumb_p: -180
    l_arm_thumb_y: 0.0
    l_arm_wr_p: 0.0
    l_arm_wr_r: 180.0
    l_arm_wr_y: -20.0
    r_arm_el_y: -59.99
    r_arm_finger45_p: -180
    r_arm_index_p: -180
    r_arm_middle_p: -180
    r_arm_sh_p1: 18.01
    r_arm_sh_p2: -5.0
    r_arm_sh_r: -75.01
    r_arm_thumb_p: -180
    r_arm_thumb_y: 0.0
    r_arm_wr_p: 0.0
    r_arm_wr_r: -180.0
    r_arm_wr_y: 15.0
    time: 0
    torso_y: 0.01
    velocity: 0
  5:
    head_p: 0.0
    head_y: 10.0
    l_arm_el_y: 60.0
    l_arm_finger45_p: -180
    l_arm_index_p: -180
    l_arm_middle_p: -180
    l_arm_sh_p1: -18.01
    l_arm_sh_p2: 5.0
    l_arm_sh_r: 74.99
    l_arm_thumb_p: -180
    l_arm_thumb_y: 0.0
    l_arm_wr_p: 0.0
    l_arm_wr_r: 180.0
    l_arm_wr_y: 20.0
    r_arm_el_y: -59.99
    r_arm_finger45_p: -180
    r_arm_index_p: -180
    r_arm_middle_p: -180
    r_arm_sh_p1: 18.01
    r_arm_sh_p2: -5.0
    r_arm_sh_r: -75.01
    r_arm_thumb_p: -180
    r_arm_thumb_y: 0.0
    r_arm_wr_p: 0.0
    r_arm_wr_r: -180.0
    r_arm_wr_y: -15.0
    time: 0
    torso_y: 0.01
    velocity: 0
  6:
    head_p: 0.0
    head_y: -10.0
    l_arm_el_y: 60.0
    l_arm_finger45_p: -180
    l_arm_index_p: -180
    l_arm_middle_p: -180
    l_arm_sh_p1: -18.01
    l_arm_sh_p2: 5.0
    l_arm_sh_r: 74.99
    l_arm_thumb_p: -180
    l_arm_thumb_y: 0.0
    l_arm_wr_p: 0.0
    l_arm_wr_r: 180.0
    l_arm_wr_y: -15.0
    r_arm_el_y: -59.99
    r_arm_finger45_p: -180
    r_arm_index_p: -180
    r_arm_middle_p: -180
    r_arm_sh_p1: 18.01
    r_arm_sh_p2: -5.0
    r_arm_sh_r: -75.01
    r_arm_thumb_p: -180
    r_arm_thumb_y: 0.0
    r_arm_wr_p: 0.0
    r_arm_wr_r: -180.0
    r_arm_wr_y: 15.0
    time: 0
    torso_y: 0.01
    velocity: 0
  7:
    head_p: 0.0
    head_y: 10.0
    l_arm_el_y: 60.0
    l_arm_finger45_p: -180
    l_arm_index_p: -180
    l_arm_middle_p: -180
    l_arm_sh_p1: -18.01
    l_arm_sh_p2: 5.0
    l_arm_sh_r: 74.99
    l_arm_thumb_p: -180
    l_arm_thumb_y: 0.0
    l_arm_wr_p: 0.0
    l_arm_wr_r: 180.0
    l_arm_wr_y: 15.0
    r_arm_el_y: -59.99
    r_arm_finger45_p: -180
    r_arm_index_p: -180
    r_arm_middle_p: -180
    r_arm_sh_p1: 18.01
    r_arm_sh_p2: -5.0
    r_arm_sh_r: -75.01
    r_arm_thumb_p: -180
    r_arm_thumb_y: 0.0
    r_arm_wr_p: 0.0
    r_arm_wr_r: -180.0
    r_arm_wr_y: -15.0
    time: 0
    torso_y: 0.01
    velocity: 0