_1st_row:
  '-': !!python/tuple
  - 386
  - 319
  '0': !!python/tuple
  - 369
  - 319
  '1': !!python/tuple
  - 221
  - 321
  '2': !!python/tuple
  - 238
  - 321
  '3': !!python/tuple
  - 256
  - 321
  '4': !!python/tuple
  - 273
  - 321
  '5': !!python/tuple
  - 291
  - 321
  '6': !!python/tuple
  - 302
  - 320
  '7': !!python/tuple
  - 318
  - 319
  '8': !!python/tuple
  - 335
  - 319
  '9': !!python/tuple
  - 352
  - 319
  '=': !!python/tuple
  - 403
  - 319
_2nd_row:
  '[': !!python/tuple
  - 396
  - 335
  ']': !!python/tuple
  - 413
  - 335
  e: !!python/tuple
  - 264
  - 334
  i: !!python/tuple
  - 346
  - 335
  o: !!python/tuple
  - 363
  - 335
  p: !!python/tuple
  - 379
  - 335
  q: !!python/tuple
  - 230
  - 335
  r: !!python/tuple
  - 281
  - 334
  t: !!python/tuple
  - 298
  - 334
  u: !!python/tuple
  - 329
  - 335
  w: !!python/tuple
  - 247
  - 334
  y: !!python/tuple
  - 313
  - 336
_3rd_row:
  '''': !!python/tuple
  - 401
  - 349
  ;: !!python/tuple
  - 383
  - 349
  a: !!python/tuple
  - 235
  - 351
  d: !!python/tuple
  - 269
  - 351
  f: !!python/tuple
  - 286
  - 351
  g: !!python/tuple
  - 304
  - 351
  h: !!python/tuple
  - 315
  - 350
  j: !!python/tuple
  - 332
  - 349
  k: !!python/tuple
  - 349
  - 349
  l: !!python/tuple
  - 366
  - 349
  s: !!python/tuple
  - 252
  - 351
_4th_row:
  ',': !!python/tuple
  - 358
  - 364
  .: !!python/tuple
  - 375
  - 364
  /: !!python/tuple
  - 392
  - 364
  b: !!python/tuple
  - 313
  - 365
  c: !!python/tuple
  - 277
  - 365
  m: !!python/tuple
  - 341
  - 364
  n: !!python/tuple
  - 324
  - 364
  v: !!python/tuple
  - 295
  - 365
  x: !!python/tuple
  - 259
  - 365
  z: !!python/tuple
  - 241
  - 366
aruco_ref:
  angle: 0.0 #1.04
  cx: 543
  cy: 286
