left_arm:
  P1:
    cx: 25.0
    cy: 443.0
    ik_x: 0.15
    ik_y: 0.24
  P2:
    cx: 22.0
    cy: 169.0
    ik_x: 0.45
    ik_y: 0.34
  P3:
    cx: 261.0
    cy: 173.0
    ik_x: 0.45
    ik_y: 0.05
  P4:
    cx: 173.0
    cy: 445.0
    ik_x: 0.15
    ik_y: 0.1
right_arm:
  P1:
    cx: 601.0
    cy: 446.0
    ik_x: 0.15
    ik_y: -0.24
  P2:
    cx: 623.0
    cy: 177.0
    ik_x: 0.45
    ik_y: -0.34
  P3:
    cx: 381.0
    cy: 174.0
    ik_x: 0.45
    ik_y: -0.05
  P4:
    cx: 456.0
    cy: 447.0
    ik_x: 0.15
    ik_y: -0.1
