left_arm:
  P1:
    cx: 22.0
    cy: 437.0
    ik_x: 0.14
    ik_y: 0.28
  P2:
    cx: 41.0
    cy: 184.0
    ik_x: 0.45
    ik_y: 0.35
  P3:
    cx: 308.0
    cy: 174.0
    ik_x: 0.45
    ik_y: 0.01
  P4:
    cx: 218.0
    cy: 432.0
    ik_x: 0.14
    ik_y: 0.08
right_arm:
  P1:
    cx: 605.0
    cy: 450.0
    ik_x: 0.14
    ik_y: -0.28
  P2:
    cx: 597.0
    cy: 198.0
    ik_x: 0.45
    ik_y: -0.35
  P3:
    cx: 333.0
    cy: 182.0
    ik_x: 0.45
    ik_y: -0.01
  P4:
    cx: 406.0
    cy: 441.0
    ik_x: 0.14
    ik_y: -0.08
