_1st_row:
  '0': !!python/tuple
  - 360
  - 330
  '1': !!python/tuple
  - 210
  - 329
  '2': !!python/tuple
  - 226
  - 329
  '3': !!python/tuple
  - 243
  - 329
  '4': !!python/tuple
  - 260
  - 329
  '5': !!python/tuple
  - 276
  - 329
  '6': !!python/tuple
  - 293
  - 329
  '7': !!python/tuple
  - 310
  - 329
  '8': !!python/tuple
  - 326
  - 329
  '9': !!python/tuple
  - 343
  - 329
_2nd_row:
  e: !!python/tuple
  - 251
  - 345
  i: !!python/tuple
  - 335
  - 345
  o: !!python/tuple
  - 352
  - 345
  p: !!python/tuple
  - 369
  - 345
  q: !!python/tuple
  - 218
  - 346
  r: !!python/tuple
  - 268
  - 345
  t: !!python/tuple
  - 285
  - 345
  u: !!python/tuple
  - 318
  - 345
  w: !!python/tuple
  - 234
  - 345
  y: !!python/tuple
  - 301
  - 345
_3rd_row:
  ;: !!python/tuple
  - 374
  - 364
  a: !!python/tuple
  - 221
  - 364
  d: !!python/tuple
  - 255
  - 364
  f: !!python/tuple
  - 272
  - 364
  g: !!python/tuple
  - 289
  - 364
  h: !!python/tuple
  - 306
  - 364
  j: !!python/tuple
  - 323
  - 364
  k: !!python/tuple
  - 340
  - 364
  l: !!python/tuple
  - 357
  - 364
  s: !!python/tuple
  - 238
  - 364
_4th_row:
  ',': !!python/tuple
  - 349
  - 381
  .: !!python/tuple
  - 366
  - 381
  /: !!python/tuple
  - 384
  - 381
  b: !!python/tuple
  - 297
  - 382
  c: !!python/tuple
  - 263
  - 382
  m: !!python/tuple
  - 332
  - 381
  n: !!python/tuple
  - 315
  - 381
  v: !!python/tuple
  - 280
  - 382
  x: !!python/tuple
  - 246
  - 382
  z: !!python/tuple
  - 229
  - 383
aruco_ref:
  angle: 0
  cx: 540
  cy: 308
